name: yessite_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.6.0
  html_unescape: ^2.0.0
  flutter_html: ^3.0.0
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.5.4
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat-regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat-bold.ttf
          weight: 900

    - family: worksans
      fonts:
        - asset: assets/fonts/worksans-regular.ttf
          weight: 400
    
  assets:
    - assets/images/titlelogo.png